/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * API & database health check
     * @description Returns the status of database connection and aggregated counts of projects, persons, and teams.
     */
    get: operations["get_app_database_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/database/init": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Initialize database and seed sample data
     * @description Creates tables in the SQLite database and seeds default test projects, teams, and persons.
     */
    post: operations["post_app_database_init"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/persons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List persons
     * @description Returns a list of persons with optional filtering by name/email, role, or team ID
     */
    get: operations["get_app_person_index"];
    put?: never;
    /**
     * Create person
     * @description Creates a new person profile with optional team and project assignments
     */
    post: operations["post_app_person_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/persons/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get person details
     * @description Returns details of a person including assigned team and participating projects
     */
    get: operations["get_app_person_show"];
    /**
     * Update person
     * @description Updates an existing person profile
     */
    put: operations["put_app_person_update"];
    post?: never;
    /**
     * Delete person
     * @description Removes a person from the system
     */
    delete: operations["delete_app_person_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List projects
     * @description Returns a list of projects with optional search in name/description and status filtering
     */
    get: operations["get_app_project_index"];
    put?: never;
    /**
     * Create project
     * @description Creates a new project and optionally assigns initial persons and teams
     */
    post: operations["post_app_project_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project details
     * @description Returns project details including directly assigned persons, teams, and all aggregated participants
     */
    get: operations["get_app_project_show"];
    /**
     * Update project
     * @description Updates an existing project and its person/team assignments
     */
    put: operations["put_app_project_update"];
    post?: never;
    /**
     * Delete project
     * @description Deletes a project from the database
     */
    delete: operations["delete_app_project_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/persons/{personId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign person to project
     * @description Adds a direct assignment of a person to the project
     */
    post: operations["post_app_project_assignperson"];
    /**
     * Remove person from project
     * @description Removes direct assignment of a person from the project
     */
    delete: operations["delete_app_project_removeperson"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/teams/{teamId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign team to project
     * @description Assigns an entire team to the project (all team members become project participants)
     */
    post: operations["post_app_project_assignteam"];
    /**
     * Remove team from project
     * @description Removes team assignment from the project
     */
    delete: operations["delete_app_project_removeteam"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List teams
     * @description Returns a list of all teams with optional search in name and description
     */
    get: operations["get_app_team_index"];
    put?: never;
    /**
     * Create team
     * @description Creates a new team with optional initial member assignments
     */
    post: operations["post_app_team_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/teams/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get team details
     * @description Returns team details including list of members and assigned projects
     */
    get: operations["get_app_team_show"];
    /**
     * Update team
     * @description Updates team name, description, or member assignments
     */
    put: operations["put_app_team_update"];
    post?: never;
    /**
     * Delete team
     * @description Removes a team from the system and unlinks members and project associations
     */
    delete: operations["delete_app_team_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @example In Progress
     * @enum {string}
     */
    ProjectStatus: "Planned" | "In Progress" | "Completed" | "On Hold";
    TeamSimple: {
      /** @example 1 */
      id: number;
      /** @example Core Platform Team */
      name: string;
      /** @example 4 */
      membersCount?: number;
    };
    PersonSimple: {
      /** @example 1 */
      id: number;
      /** @example John Smith */
      name: string;
      /**
       * Format: email
       * @example john.smith@example.com
       */
      email: string;
      /** @example Project Lead */
      role: string;
      team?: components["schemas"]["TeamSimple"] | null;
    };
    ProjectSimple: {
      /** @example 1 */
      id: number;
      /** @example Information Portal & Data Warehouse */
      name: string;
      /** @example Comprehensive modernization of internal project reporting and data lakes */
      description?: string | null;
      status: components["schemas"]["ProjectStatus"];
      /**
       * Format: date
       * @example 2026-01-15
       */
      startDate?: string | null;
      /**
       * Format: date
       * @example 2026-12-31
       */
      endDate?: string | null;
      /** @example 2 */
      directPersonsCount: number;
      /** @example 2 */
      teamsCount: number;
      /** @example 5 */
      totalParticipantsCount: number;
      /**
       * Format: date-time
       * @example 2026-10-03T12:00:00+00:00
       */
      createdAt: string;
    };
    Participant: {
      /** @example 1 */
      id: number;
      /** @example John Smith */
      name: string;
      /**
       * Format: email
       * @example john.smith@example.com
       */
      email: string;
      /** @example Project Lead */
      role: string;
      /**
       * @example both
       * @enum {string}
       */
      assignmentType: "direct" | "team" | "both";
      team?: components["schemas"]["TeamSimple"] | null;
      viaTeam?: components["schemas"]["TeamSimple"] | null;
    };
    ProjectDetail: components["schemas"]["ProjectSimple"] & {
      persons: components["schemas"]["PersonSimple"][];
      teams: components["schemas"]["TeamSimple"][];
      allParticipants: components["schemas"]["Participant"][];
    };
    PersonDetail: components["schemas"]["PersonSimple"] & {
      /** @example 2 */
      projectsCount: number;
      /**
       * Format: date-time
       * @example 2026-10-03T12:00:00+00:00
       */
      createdAt: string;
      projects?: {
        /** @example 1 */
        id: number;
        /** @example Information Portal */
        name: string;
        status: components["schemas"]["ProjectStatus"];
        /** Format: date */
        startDate?: string | null;
        /** Format: date */
        endDate?: string | null;
      }[];
    };
    TeamDetail: {
      /** @example 1 */
      id: number;
      /** @example Core Platform Team */
      name: string;
      /** @example Team responsible for core architecture and microservices */
      description?: string | null;
      /** @example 4 */
      membersCount: number;
      /** @example 2 */
      projectsCount: number;
      /** Format: date-time */
      createdAt: string;
      members?: {
        id: number;
        name: string;
        email: string;
        role: string;
      }[];
      projects?: {
        id: number;
        name: string;
        status: components["schemas"]["ProjectStatus"];
      }[];
    };
    ProjectInput: {
      /** @example Strategic Cybersecurity Cloud */
      name: string;
      /** @example Comprehensive SIEM implementation and threat monitoring */
      description?: string | null;
      status: components["schemas"]["ProjectStatus"];
      /**
       * Format: date
       * @example 2026-02-01
       */
      startDate?: string | null;
      /**
       * Format: date
       * @example 2026-11-30
       */
      endDate?: string | null;
      /**
       * @example [
       *       1,
       *       2
       *     ]
       */
      personIds?: number[];
      /**
       * @example [
       *       1
       *     ]
       */
      teamIds?: number[];
    };
    PersonInput: {
      /** @example Peter Parker */
      name: string;
      /**
       * Format: email
       * @example peter.parker@example.com
       */
      email: string;
      /** @example DevOps Engineer */
      role: string;
      /** @example 1 */
      teamId?: number | null;
      /**
       * @example [
       *       1
       *     ]
       */
      projectIds?: number[];
    };
    TeamInput: {
      /** @example DevOps & Infrastructure */
      name: string;
      /** @example Cloud orchestration and Kubernetes clusters */
      description?: string | null;
      /**
       * @example [
       *       1,
       *       3
       *     ]
       */
      memberIds?: number[];
    };
    HealthStatus: {
      /** @example OK */
      status: string;
      /** @example Project Management REST API */
      service: string;
      /** @example connected */
      database: string;
      stats: {
        /** @example 3 */
        projects: number;
        /** @example 6 */
        persons: number;
        /** @example 3 */
        teams: number;
      };
      /** Format: date-time */
      timestamp: string;
    };
    ApiResponseProjectList: {
      /** @example true */
      success: boolean;
      /** @example 3 */
      count?: number;
      data: components["schemas"]["ProjectSimple"][];
    };
    ApiResponseProjectDetail: {
      /** @example true */
      success: boolean;
      data: components["schemas"]["ProjectDetail"];
    };
    ApiResponsePersonList: {
      /** @example true */
      success: boolean;
      /** @example 6 */
      count?: number;
      data: components["schemas"]["PersonSimple"][];
    };
    ApiResponsePersonDetail: {
      /** @example true */
      success: boolean;
      data: components["schemas"]["PersonDetail"];
    };
    ApiResponseTeamList: {
      /** @example true */
      success: boolean;
      /** @example 3 */
      count?: number;
      data: components["schemas"]["TeamSimple"][];
    };
    ApiResponseTeamDetail: {
      /** @example true */
      success: boolean;
      data: components["schemas"]["TeamDetail"];
    };
    ApiResponseSuccessMessage: {
      /** @example true */
      success: boolean;
      /** @example Operation was successful */
      message: string;
    };
    ApiErrorResponse: {
      /** @example false */
      success: boolean;
      /** @example Item not found */
      message?: string;
      /**
       * @example {
       *       "name": "Project name is required"
       *     }
       */
      errors?: {
        [key: string]: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_app_database_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description System is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
  post_app_database_init: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Database initialized successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSuccessMessage"];
        };
      };
    };
  };
  get_app_person_index: {
    parameters: {
      query?: {
        /** @description Search in name, email, and role */
        search?: string;
        /** @description Filter by exact role */
        role?: string;
        /** @description Filter by team ID */
        teamId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of persons */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponsePersonList"];
        };
      };
    };
  };
  post_app_person_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonInput"];
      };
    };
    responses: {
      /** @description Person was successfully created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponsePersonDetail"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  get_app_person_show: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Person ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Person details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponsePersonDetail"];
        };
      };
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  put_app_person_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Person ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonInput"];
      };
    };
    responses: {
      /** @description Person was successfully updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponsePersonDetail"];
        };
      };
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_app_person_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Person ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Person was successfully deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSuccessMessage"];
        };
      };
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  get_app_project_index: {
    parameters: {
      query?: {
        /** @description Search query in project name or description */
        search?: string;
        /** @description Filter by project status */
        status?: components["schemas"]["ProjectStatus"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectList"];
        };
      };
    };
  };
  post_app_project_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectInput"];
      };
    };
    responses: {
      /** @description Project was successfully created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  get_app_project_show: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  put_app_project_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectInput"];
      };
    };
    responses: {
      /** @description Project was successfully updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_app_project_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project was successfully deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSuccessMessage"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  post_app_project_assignperson: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
        /** @description Person ID */
        personId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Person was assigned to project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project or person not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_app_project_removeperson: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
        /** @description Person ID */
        personId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Person was removed from project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project or person not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  post_app_project_assignteam: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
        /** @description Team ID */
        teamId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team was assigned to project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project or team not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_app_project_removeteam: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: number;
        /** @description Team ID */
        teamId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team was removed from project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseProjectDetail"];
        };
      };
      /** @description Project or team not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  get_app_team_index: {
    parameters: {
      query?: {
        /** @description Search in team name and description */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of teams */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseTeamList"];
        };
      };
    };
  };
  post_app_team_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamInput"];
      };
    };
    responses: {
      /** @description Team was successfully created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseTeamDetail"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  get_app_team_show: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Team ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseTeamDetail"];
        };
      };
      /** @description Team not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  put_app_team_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Team ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamInput"];
      };
    };
    responses: {
      /** @description Team was successfully updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseTeamDetail"];
        };
      };
      /** @description Team not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_app_team_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Team ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team was successfully deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSuccessMessage"];
        };
      };
      /** @description Team not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
}
